package com.bs.glr.bean;

public class AttributeTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_table.id
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_table.aname
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    private String aname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_table.material
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    private String material;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_table.color
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    private String color;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_table.id
     *
     * @return the value of attribute_table.id
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_table.id
     *
     * @param id the value for attribute_table.id
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_table.aname
     *
     * @return the value of attribute_table.aname
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_table.aname
     *
     * @param aname the value for attribute_table.aname
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_table.material
     *
     * @return the value of attribute_table.material
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_table.material
     *
     * @param material the value for attribute_table.material
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_table.color
     *
     * @return the value of attribute_table.color
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_table.color
     *
     * @param color the value for attribute_table.color
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }
}