package com.bs.glr.bean;

public class ClothingCategoryTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clothing_category_table.id
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clothing_category_table.category_name
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    private String categoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clothing_category_table.id
     *
     * @return the value of clothing_category_table.id
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clothing_category_table.id
     *
     * @param id the value for clothing_category_table.id
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clothing_category_table.category_name
     *
     * @return the value of clothing_category_table.category_name
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clothing_category_table.category_name
     *
     * @param categoryName the value for clothing_category_table.category_name
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }
}