package com.bs.glr.mapper;

import com.bs.glr.bean.AttributeTable;
import com.bs.glr.bean.AttributeTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttributeTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    long countByExample(AttributeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int deleteByExample(AttributeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int insert(AttributeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int insertSelective(AttributeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    List<AttributeTable> selectByExample(AttributeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    AttributeTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int updateByExampleSelective(@Param("record") AttributeTable record, @Param("example") AttributeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int updateByExample(@Param("record") AttributeTable record, @Param("example") AttributeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int updateByPrimaryKeySelective(AttributeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int updateByPrimaryKey(AttributeTable record);
}