package com.bs.glr.mapper;

import com.bs.glr.bean.ClothingCategoryTable;
import com.bs.glr.bean.ClothingCategoryTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClothingCategoryTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clothing_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    long countByExample(ClothingCategoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clothing_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int deleteByExample(ClothingCategoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clothing_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clothing_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int insert(ClothingCategoryTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clothing_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int insertSelective(ClothingCategoryTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clothing_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    List<ClothingCategoryTable> selectByExample(ClothingCategoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clothing_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    ClothingCategoryTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clothing_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int updateByExampleSelective(@Param("record") ClothingCategoryTable record, @Param("example") ClothingCategoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clothing_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int updateByExample(@Param("record") ClothingCategoryTable record, @Param("example") ClothingCategoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clothing_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int updateByPrimaryKeySelective(ClothingCategoryTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clothing_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int updateByPrimaryKey(ClothingCategoryTable record);
}