package com.bs.glr.mapper;

import com.bs.glr.bean.WardrobeCategoryTable;
import com.bs.glr.bean.WardrobeCategoryTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WardrobeCategoryTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardrobe_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    long countByExample(WardrobeCategoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardrobe_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int deleteByExample(WardrobeCategoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardrobe_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardrobe_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int insert(WardrobeCategoryTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardrobe_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int insertSelective(WardrobeCategoryTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardrobe_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    List<WardrobeCategoryTable> selectByExample(WardrobeCategoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardrobe_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    WardrobeCategoryTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardrobe_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int updateByExampleSelective(@Param("record") WardrobeCategoryTable record, @Param("example") WardrobeCategoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardrobe_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int updateByExample(@Param("record") WardrobeCategoryTable record, @Param("example") WardrobeCategoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardrobe_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int updateByPrimaryKeySelective(WardrobeCategoryTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardrobe_category_table
     *
     * @mbg.generated Fri Apr 12 15:11:06 CST 2024
     */
    int updateByPrimaryKey(WardrobeCategoryTable record);
}